### ISSUE TITLE
Please give credit to haslettj in the readme

### ISSUE THREAD

**Issue by tubalainen** [nootropicdesign/wx-ground-station#1]
Great project and for making a great setup even greater with the AWS setup!

Please give credit to the original creator of the of the shell scripts to share the love!
https://www.instructables.com/id/Raspberry-Pi-NOAA-Weather-Satellite-Receiver/

**Comment by nootropicdesign** [comment]
You're right, thanks. I gave him plenty of credit in my full article, but it should be here, also.
