### ISSUE TITLE
WAVE: RIFF header not found

### ISSUE THREAD

**Issue by ChadOhman** [nootropicdesign/wx-ground-station#2]
Hey there,

I built out my ground station with a more permanent QFH antenna and integrated pi after running a temporary install for a couple of months with your build. Strangely I'm not picking up any passes and the mailbox /var/mail/pi is filling up with these messages. Have you seen this before? This is on a fresh updated Raspbian install following your guide.

`Return-path: <pi@satpi>
Envelope-to: pi@satpi
Delivery-date: Thu, 09 Jan 2020 23:10:03 -0700
Received: from pi by satpi with local (Exim 4.92)
        (envelope-from <pi@satpi>)
        id 1ipnUh-0001OU-DK
        for pi@satpi; Thu, 09 Jan 2020 23:10:03 -0700
Subject: Output from your job       43
To: pi@satpi
Message-Id: <E1ipnUh-0001OU-DK@satpi>
From: pi@satpi
Date: Thu, 09 Jan 2020 23:10:03 -0700

sox FAIL formats: can't open input  -': WAVE: RIFF header not found`

Thanks!

**Comment by nootropicdesign** [comment]
This is because you are not using the correct version of rtl-sdr that supports the WAV file header in the data. The article states that you need to use [this version](https://github.com/keenerd/rtl-sdr).

**Comment by ChadOhman** [comment]
Oh boy. I'd configured the pi over a couple of days and didn't realize that I didn't install the correct version. Thanks Michael. 73!

**Comment by nootropicdesign** [comment]
Well, I had the exact same problem when I started this project, so I knew the error well!

**Comment by ChadOhman** [comment]
Thank you - this is really the best implementation of what we're trying to accomplish!
I think you'd helped me with this error before but I can't find any record of it - if you're getting an access denied under Recent Captures?

**Comment by nootropicdesign** [comment]
The permission problem has to do with all the AWS setup. Carefully recheck the steps I documented in the article. It's very detail oriented and any missed step will cause access issues.

**Comment by ChadOhman** [comment]
Got it. Recreated the bucket/permissions/identity pool/policy/etc.

We're live! http://lambnet-noaa.s3-website.ca-central-1.amazonaws.com/

Thanks again for your help!
